name: Print Current Time on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  print-time:
    runs-on: ubuntu-latest

    steps:
    - name: Set Environment Variable
      run: echo "CURRENT_TIME=$(date +'%T')" >> $GITHUB_ENV

    - name: Print Current Time
      run: echo "Current Time: $CURRENT_TIME"
